[package]
name = "magma_render"
version = "0.1.0"
edition = "2021"

[dependencies]
magma_ecs = "0.1.0-alpha.5"
wgpu = "22.1.0"
winit = { version = "0.30.5", features = ["rwh_05"] }
pollster = "0.3.0"

[dev-dependencies]
env_logger = "0.11.5"

[[test]]
name = "render_state"
harness = false
